Repository AY2021S1-CS2103-F09-2/tp, pull requests merged in 2020-11, with the labels that each got.

#226 Fix bug for Undo
  src/main/java/seedu/pivot/logic/commands/ClearCommand.java
  src/main/java/seedu/pivot/logic/commands/Page.java
  src/main/java/seedu/pivot/logic/commands/RedoCommand.java
  src/main/java/seedu/pivot/logic/commands/UndoCommand.java
  src/main/java/seedu/pivot/logic/commands/Undoable.java
  src/main/java/seedu/pivot/logic/commands/archivecommands/ArchiveCommand.java
  src/main/java/seedu/pivot/logic/commands/archivecommands/UnarchiveCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/AddCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/AddDescriptionCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/DeleteCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/EditStatusCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/EditTitleCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/AddDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/DeleteDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/EditDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/AddSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/DeleteSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/EditSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/AddVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/DeleteVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/EditVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/AddWitnessCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/DeleteWitnessCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/EditWitnessCommand.java
  src/main/java/seedu/pivot/model/Model.java
  src/main/java/seedu/pivot/model/ModelManager.java
  src/main/java/seedu/pivot/model/VersionedPivot.java
  src/main/java/seedu/pivot/ui/MainWindow.java
  src/test/java/seedu/pivot/logic/commands/ArchiveCommandTest.java
  src/test/java/seedu/pivot/logic/commands/RedoCommandIntegrationTest.java
  src/test/java/seedu/pivot/logic/commands/RedoCommandTest.java
  src/test/java/seedu/pivot/logic/commands/UnarchiveCommandTest.java
  src/test/java/seedu/pivot/logic/commands/UndoCommandIntegrationTest.java
  src/test/java/seedu/pivot/logic/commands/UndoCommandTest.java
  src/test/java/seedu/pivot/logic/commands/casecommands/AddCaseCommandTest.java
  src/test/java/seedu/pivot/logic/commands/casecommands/AddDescriptionCommandTest.java
  src/test/java/seedu/pivot/logic/commands/casecommands/DeleteCaseCommandTest.java
  src/test/java/seedu/pivot/logic/commands/documentcommands/AddDocumentCommandTest.java
  src/test/java/seedu/pivot/logic/commands/documentcommands/DeleteDocumentCommandTest.java
  src/test/java/seedu/pivot/logic/commands/suspectcommands/AddSuspectCommandTest.java
  src/test/java/seedu/pivot/logic/commands/suspectcommands/DeleteSuspectCommandTest.java
  src/test/java/seedu/pivot/logic/commands/testutil/ModelStub.java
  src/test/java/seedu/pivot/logic/commands/victimcommands/AddVictimCommandTest.java
  src/test/java/seedu/pivot/logic/commands/victimcommands/DeleteVictimCommandTest.java
  src/test/java/seedu/pivot/logic/commands/witnesscommands/AddWitnessCommandTest.java
  src/test/java/seedu/pivot/logic/commands/witnesscommands/DeleteWitnessCommandTest.java
  src/test/java/seedu/pivot/model/VersionedPivotTest.java
Labels: priority.High, type.Bug

#231 [v1.4.1] Handle duplicates and invalid index for edit and add
  src/main/java/seedu/pivot/commons/core/UserMessages.java
  src/main/java/seedu/pivot/logic/commands/casecommands/EditTitleCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/AddDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/EditDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/AddSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/EditSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/AddVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/EditVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/AddWitnessCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/EditWitnessCommand.java
  src/main/java/seedu/pivot/logic/parser/ParserUtil.java
  src/main/java/seedu/pivot/model/investigationcase/Case.java
  src/main/java/seedu/pivot/model/investigationcase/Reference.java
  src/test/java/seedu/pivot/logic/commands/documentcommands/AddDocumentCommandIntegrationTest.java
  src/test/java/seedu/pivot/logic/commands/documentcommands/AddDocumentCommandTest.java
  src/test/java/seedu/pivot/logic/commands/suspectcommands/AddSuspectCommandIntegrationTest.java
  src/test/java/seedu/pivot/logic/commands/suspectcommands/AddSuspectCommandTest.java
  src/test/java/seedu/pivot/logic/commands/victimcommands/AddVictimCommandIntegrationTest.java
  src/test/java/seedu/pivot/logic/commands/victimcommands/AddVictimCommandTest.java
  src/test/java/seedu/pivot/logic/commands/witnesscommands/AddWitnessCommandIntegrationTest.java
  src/test/java/seedu/pivot/logic/commands/witnesscommands/AddWitnessCommandTest.java
  src/test/java/seedu/pivot/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/pivot/logic/parser/OpenCommandParserTest.java
  src/test/java/seedu/pivot/model/investigationcase/CaseTest.java
Labels: priority.High, type.Task

#234 Minor bug fix
  src/test/java/seedu/pivot/logic/commands/documentcommands/EditDocumentCommandTest.java
Labels: type.Bug

#237 Add tests for edit commands
  src/main/java/seedu/pivot/logic/commands/EditCommand.java
  src/test/java/seedu/pivot/logic/commands/EditCommandTest.java
  src/test/java/seedu/pivot/logic/commands/casecommands/EditStatusCommandTest.java
  src/test/java/seedu/pivot/logic/commands/casecommands/EditTitleCommandTest.java
  src/test/java/seedu/pivot/logic/commands/documentcommands/EditDocumentCommandIntegrationTest.java
  src/test/java/seedu/pivot/logic/parser/EditCommandParserTest.java
Labels: priority.Medium, type.Enhancement

#236 Update user guide for case page (excluding description and persons)
  docs/UserGuide.md
Labels: type.Enhancement

#240 [v1.4] Update PPP
  docs/AboutUs.md
  docs/team/vielheim.md
  src/main/java/seedu/pivot/model/investigationcase/caseperson/Email.java
Labels: priority.High

#245 [v1.4] Update UserGuide and Add Credits
  docs/UserGuide.md
  src/main/java/seedu/pivot/commons/util/StringUtil.java
  src/main/java/seedu/pivot/model/investigationcase/caseperson/Email.java
Labels: priority.High, type.Task

#247 [v1.4] Update Code Quality
  src/main/java/seedu/pivot/logic/commands/AddCommand.java
  src/main/java/seedu/pivot/logic/commands/Command.java
  src/main/java/seedu/pivot/logic/commands/DeleteCommand.java
  src/main/java/seedu/pivot/logic/commands/EditCommand.java
  src/main/java/seedu/pivot/logic/commands/EditPersonCommand.java
  src/main/java/seedu/pivot/logic/commands/ListCommand.java
  src/main/java/seedu/pivot/logic/commands/ListTabCommand.java
  src/main/java/seedu/pivot/logic/commands/OpenCommand.java
  src/main/java/seedu/pivot/logic/commands/Page.java
  src/main/java/seedu/pivot/logic/commands/RedoCommand.java
  src/main/java/seedu/pivot/logic/commands/ReturnCommand.java
  src/main/java/seedu/pivot/logic/commands/UndoCommand.java
  src/main/java/seedu/pivot/logic/commands/Undoable.java
  src/main/java/seedu/pivot/logic/commands/archivecommands/ArchiveCommand.java
  src/main/java/seedu/pivot/logic/commands/archivecommands/ListArchiveCommand.java
  src/main/java/seedu/pivot/logic/commands/archivecommands/UnarchiveCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/AddCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/DeleteCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/EditStatusCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/EditTitleCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/ListCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/OpenCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/descriptioncommands/AddDescriptionCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/descriptioncommands/DeleteDescriptionCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/descriptioncommands/EditDescriptionCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/AddDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/DeleteDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/EditDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/OpenDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/AddSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/DeleteSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/EditSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/AddVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/DeleteVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/EditVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/AddWitnessCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/DeleteWitnessCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/EditWitnessCommand.java
  src/main/java/seedu/pivot/logic/parser/AddCaseCommandParser.java
  src/main/java/seedu/pivot/logic/parser/CliSyntax.java
  src/main/java/seedu/pivot/logic/parser/ListCommandParser.java
  src/test/java/seedu/pivot/logic/commands/EditCaseDescriptorTest.java
  src/test/java/seedu/pivot/logic/commands/testutil/CommandTestUtil.java
  src/test/java/seedu/pivot/logic/parser/AddCaseCommandParserTest.java
  src/test/java/seedu/pivot/logic/parser/PivotParserTest.java
  src/test/java/seedu/pivot/testutil/CaseUtil.java
  src/test/java/seedu/pivot/testutil/EditCaseDescriptorBuilder.java
  src/test/java/seedu/pivot/testutil/TypicalCases.java
Labels: priority.Medium

#246 [v1.4] Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/StateClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/StateClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Enhancement

#252 [v1.4] Update UserGuide.md
  docs/UserGuide.md
  src/main/java/seedu/pivot/commons/core/UserMessages.java
Labels: priority.Medium

#253 [v1.4] Fix GUI bug
  src/main/java/seedu/pivot/ui/MainWindow.java
Labels: priority.High

#256 Update PPP
  docs/team/jargonx.md
Labels: priority.High, type.Task

#262 Update use cases and User stories
  docs/DeveloperGuide.md
  docs/diagrams/OpenCaseSequenceDiagram.puml
  docs/images/OpenCaseSequenceDiagram.png
Labels: type.Enhancement, type.Story

#264 Minor addition to Add Description in UG
  docs/UserGuide.md
Labels: priority.Medium, type.Enhancement

#267 Update Portfolio Reference Neil and Esmanda
  docs/AboutUs.md
Labels: priority.High
