Repository AY2021S1-CS2103-F09-2/tp, pull requests merged in 2020-10, with the labels that each got.

#77 Update Person to contain list of Victims
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Victim.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedVictim.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#78 Update Person to contain list of Suspects
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Suspect.java
  src/main/java/seedu/address/model/person/Victim.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSuspect.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Task

#82 Add Alphanumeric class
  src/main/java/seedu/address/model/person/Alphanumeric.java
  src/main/java/seedu/address/model/person/Name.java
Labels: priority.High, type.Task

#80 Add Status field to Person
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#79 Add Document to Person class
  references/test1.txt
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Document.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Reference.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedDocument.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#89 Update Alphanumeric Class
  src/main/java/seedu/address/model/person/Alphanumeric.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedDocument.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSuspect.java
  src/main/java/seedu/address/storage/JsonAdaptedVictim.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: severity.High, type.Bug, type.Enhancement

#76 Update Person to contain list of Witnesses
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Witness.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedWitness.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#85 Edit Delete Command to "delete case [INDEX]"
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High, type.Story

#104 Branch changing alphanumeric
  src/main/java/seedu/address/model/person/Alphanumeric.java
  src/main/java/seedu/address/model/person/Name.java
Labels: type.Enhancement, type.Task

#81 [v1.2.2] Add Description field to Person
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Alphanumeric.java
  src/main/java/seedu/address/model/person/Description.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Task

#83 [v1.2.2] Edit list command to 'list case'
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Story

#100 [v1.2.3] Add Title class and Refactor Name Attribute for Case
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Title.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#106 [v1.2.3] Remove Address from Person Class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#101 [v1.2.3] Delete Email Field from Person Class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#107 [v1.2.3] Delete Phone from Person Class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#109 [v1.2.4] Add State to PIVOT
  src/main/java/seedu/address/logic/state/StateManager.java
Labels: priority.High, type.Task

#121 [v1.2.4] Add Return Command
  src/main/java/seedu/address/logic/commands/ReturnCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.High, type.Task

#114 [v1.2.4] Change DeleteCommand Class into abstract class
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/casecommands/DeleteCaseCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCaseCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High, type.Task

#119 [v1.2.4] Make list command abstract
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ListCaseCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCaseCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: priority.High, type.Task

#118 [v1.2.4] Make AddCommand abstract and add AddCaseCommand
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/casecommands/AddCaseCommand.java
  src/main/java/seedu/address/logic/commands/casecommands/ListCaseCommand.java
  src/main/java/seedu/address/logic/commands/casecommands/OpenCaseCommand.java
  src/main/java/seedu/address/logic/parser/AddCaseCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/OpenCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCaseCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCaseCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCaseCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCaseCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: priority.High, type.Task

#122 [v1.2.4] Minor Update to OpenCommandParser.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/OpenCommandParser.java
Labels: priority.High, type.Task

#128 [v1.2.5] Add document to opened investigation case
  src/main/java/seedu/address/logic/commands/AddDocumentCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddDocumentCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/investigationcase/Document.java
  src/main/java/seedu/address/model/investigationcase/Reference.java
Labels: priority.High, type.Task

#126 [v1.2.5] Add Description to opened Investigation Case
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/casecommands/AddCaseCommand.java
  src/main/java/seedu/address/logic/commands/casecommands/AddDescriptionCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddDescriptionCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High, type.Task

#130 [v1.2.5] Add and Delete Suspect to opened Investigation Case
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/casecommands/AddCaseCommand.java
  src/main/java/seedu/address/logic/commands/suspectcommands/AddSuspectCommand.java
  src/main/java/seedu/address/logic/commands/suspectcommands/DeleteSuspectCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSuspectCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/parser/AddSuspectCommandParserTest.java
Labels: priority.High, type.Task

#133 [v1.2.5] Add and Delete Witness
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/witnesscommands/AddWitnessCommand.java
  src/main/java/seedu/address/logic/commands/witnesscommands/DeleteWitnessCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddWitnessCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: priority.High, type.Epic

#132 [v1.2.5] GUI Updates
  src/main/java/seedu/address/logic/state/StateManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiStateManager.java
Labels: priority.High, type.Task

#131 [v1.2.5] Deleting document from case
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/OpenCommand.java
  src/main/java/seedu/address/logic/commands/casecommands/AddDescriptionCommand.java
  src/main/java/seedu/address/logic/commands/documentcommands/AddDocumentCommand.java
  src/main/java/seedu/address/logic/commands/documentcommands/DeleteDocumentCommand.java
  src/main/java/seedu/address/logic/commands/victimcommands/AddVictimCommand.java
  src/main/java/seedu/address/logic/commands/victimcommands/DeleteVictimCommand.java
  src/main/java/seedu/address/logic/parser/AddDocumentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Task

#135 [v1.3.1] Update User Guide
  docs/UserGuide.md
Labels: priority.High, type.Task

#140 [v1.3.1] Improve code quality and standardisation
  build.gradle
  src/main/java/seedu/pivot/commons/core/Messages.java
  src/main/java/seedu/pivot/logic/commands/AddCommand.java
  src/main/java/seedu/pivot/logic/commands/Command.java
  src/main/java/seedu/pivot/logic/commands/DeleteCommand.java
  src/main/java/seedu/pivot/logic/commands/ListCommand.java
  src/main/java/seedu/pivot/logic/commands/OpenCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/DeleteCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/ListCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/OpenCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/DeleteDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/DeleteSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/DeleteVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/DeleteWitnessCommand.java
  src/main/java/seedu/pivot/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/pivot/logic/parser/OpenCommandParser.java
  src/main/java/seedu/pivot/logic/parser/ParserUtil.java
  src/main/java/seedu/pivot/model/investigationcase/Alphanumeric.java
  src/main/java/seedu/pivot/model/investigationcase/Case.java
  src/main/java/seedu/pivot/model/util/SampleDataUtil.java
  src/main/java/seedu/pivot/storage/JsonAdaptedVictim.java
  src/main/java/seedu/pivot/storage/JsonAdaptedWitness.java
  src/test/data/JsonSerializablePivotTest/typicalPersonsPivot.json
  src/test/java/seedu/pivot/logic/LogicManagerTest.java
  src/test/java/seedu/pivot/logic/commands/ListCaseCommandTest.java
  src/test/java/seedu/pivot/testutil/TypicalCases.java
Labels: priority.High, type.Task

#138 [v1.3.1] Code Quality and Standardisation
  src/main/java/seedu/pivot/logic/commands/AddCommand.java
  src/main/java/seedu/pivot/logic/commands/ClearCommand.java
  src/main/java/seedu/pivot/logic/commands/DeleteCommand.java
  src/main/java/seedu/pivot/logic/commands/EditCommand.java
  src/main/java/seedu/pivot/logic/commands/ReturnCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/AddCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/AddDescriptionCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/AddDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/AddSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/AddVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/AddWitnessCommand.java
  src/main/java/seedu/pivot/logic/parser/AddCaseCommandParser.java
  src/main/java/seedu/pivot/logic/parser/AddCommandParser.java
  src/main/java/seedu/pivot/logic/parser/AddDescriptionCommandParser.java
  src/main/java/seedu/pivot/logic/parser/AddDocumentCommandParser.java
  src/main/java/seedu/pivot/logic/parser/AddSuspectCommandParser.java
  src/main/java/seedu/pivot/logic/parser/AddVictimCommandParser.java
  src/main/java/seedu/pivot/logic/parser/AddWitnessCommandParser.java
  src/main/java/seedu/pivot/logic/parser/CliSyntax.java
  src/main/java/seedu/pivot/logic/parser/EditCommandParser.java
  src/main/java/seedu/pivot/logic/parser/ListCommandParser.java
  src/main/java/seedu/pivot/logic/parser/ParserUtil.java
  src/main/java/seedu/pivot/model/investigationcase/Alphanumeric.java
  src/main/java/seedu/pivot/model/investigationcase/Case.java
  src/main/java/seedu/pivot/model/investigationcase/Document.java
  src/main/java/seedu/pivot/model/investigationcase/NameContainsKeywordsPredicate.java
  src/main/java/seedu/pivot/model/investigationcase/Reference.java
  src/main/java/seedu/pivot/model/investigationcase/Status.java
  src/main/java/seedu/pivot/model/investigationcase/Suspect.java
  src/main/java/seedu/pivot/model/investigationcase/Victim.java
  src/main/java/seedu/pivot/model/investigationcase/Witness.java
  src/main/java/seedu/pivot/storage/JsonAdaptedCase.java
  src/main/java/seedu/pivot/storage/JsonAdaptedDocument.java
  src/main/java/seedu/pivot/storage/JsonAdaptedSuspect.java
  src/main/java/seedu/pivot/storage/JsonAdaptedVictim.java
  src/main/java/seedu/pivot/storage/JsonAdaptedWitness.java
  src/main/java/seedu/pivot/ui/CasePersonCard.java
  src/main/java/seedu/pivot/ui/DocumentCard.java
  src/main/java/seedu/pivot/ui/MainWindow.java
  src/main/java/seedu/pivot/ui/PersonCard.java
  src/test/java/seedu/pivot/logic/commands/AddCaseCommandIntegrationTest.java
  src/test/java/seedu/pivot/logic/commands/AddCaseCommandTest.java
  src/test/java/seedu/pivot/logic/commands/ClearCommandTest.java
  src/test/java/seedu/pivot/logic/commands/CommandTestUtil.java
  src/test/java/seedu/pivot/model/ModelManagerTest.java
  src/test/java/seedu/pivot/testutil/CaseUtil.java
Labels: priority.High, type.Task

#145 [v1.3.2] Update Undo Feature in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoSequenceDiagram.png
Labels: priority.High, type.Task

#146 [v1.3.2] Add Logging for Delete, Open and Return Commands
  src/main/java/seedu/pivot/logic/commands/ReturnCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/DeleteCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/OpenCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/DeleteDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/DeleteSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/DeleteVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/DeleteWitnessCommand.java
Labels: priority.Low, type.Task

#147 [v1.3.2] Update developer guide model and storage component
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: priority.High, type.Task

#149 [v.1.3.2] Update Developer Guide with for State and Ui
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/OpenCaseSequenceDiagram.puml
  docs/diagrams/ReturnSequenceDiagram.puml
  docs/diagrams/StateClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiStateSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/OpenCaseSequenceDiagram.png
  docs/images/ReturnSequenceDiagram.png
  docs/images/StateClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UiStateSequenceDiagram.png
Labels: priority.High, type.Task

#143 [v1.3.2] Add logging to GUI and JSON Storage files
  src/main/java/seedu/pivot/logic/state/StateManager.java
  src/main/java/seedu/pivot/storage/JsonAdaptedCase.java
  src/main/java/seedu/pivot/storage/JsonAdaptedDocument.java
  src/main/java/seedu/pivot/storage/JsonAdaptedSuspect.java
  src/main/java/seedu/pivot/storage/JsonAdaptedVictim.java
  src/main/java/seedu/pivot/storage/JsonAdaptedWitness.java
  src/main/java/seedu/pivot/storage/JsonSerializablePivot.java
  src/main/java/seedu/pivot/ui/MainWindow.java
  src/main/java/seedu/pivot/ui/UiStateManager.java
Labels: priority.Low, type.Task

#144 [v1.3.2] Add logging to add/list commands
  src/main/java/seedu/pivot/logic/commands/casecommands/AddCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/AddDescriptionCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/ListCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/AddDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/AddSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/AddVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/AddWitnessCommand.java
Labels: priority.Low, type.Task

#148 [v1.3.2] Update DeveloperGuide with Document Implementation
  docs/DeveloperGuide.md
  docs/images/AddDocumentDiagram.PNG
  docs/images/DeleteDocumentDiagram.PNG
  docs/images/DocumentClassDiagram.png
Labels: priority.High, type.Task

#150 Update Undo in Developer Guide
  docs/DeveloperGuide.md
Labels: priority.Low, type.Task

#151 Update naming in DG
  docs/images/AddDocumentDiagram.png
  docs/images/DeleteDocumentDiagram.png
Labels: type.Bug

#152 Add asserts in AddVictimCommandParser
  src/main/java/seedu/pivot/logic/parser/AddVictimCommandParser.java
Labels: priority.High, type.Task

#154 Update Logic in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: priority.High, type.Task

#155 [v1.3.2] Add support for Opening Document
  src/main/java/seedu/pivot/commons/core/Messages.java
  src/main/java/seedu/pivot/commons/util/FileUtil.java
  src/main/java/seedu/pivot/logic/commands/Command.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/OpenDocumentCommand.java
  src/main/java/seedu/pivot/logic/parser/OpenCommandParser.java
  src/main/java/seedu/pivot/model/investigationcase/Reference.java
  src/main/java/seedu/pivot/storage/ReferenceStorage.java
Labels: priority.High, type.Task

#161 [v1.3.2] Add Tests to Reference, Document, ReferenceStorage, OpenCommands
  references/test1.txt
  src/main/java/seedu/pivot/MainApp.java
  src/main/java/seedu/pivot/model/investigationcase/Reference.java
  src/main/java/seedu/pivot/storage/ReferenceStorage.java
  src/main/java/seedu/pivot/storage/StorageManager.java
  src/test/java/seedu/pivot/commons/util/FileUtilTest.java
  src/test/java/seedu/pivot/logic/LogicManagerTest.java
  src/test/java/seedu/pivot/logic/commands/EditCommandTest.java
  src/test/java/seedu/pivot/logic/commands/OpenCaseCommandTest.java
  src/test/java/seedu/pivot/logic/commands/OpenDocumentCommandTest.java
  src/test/java/seedu/pivot/logic/commands/ReturnCommandTest.java
  src/test/java/seedu/pivot/logic/commands/casecommands/AddCaseCommandTest.java
  src/test/java/seedu/pivot/logic/commands/casecommands/ListCaseCommandTest.java
  src/test/java/seedu/pivot/model/investigationcase/DocumentTest.java
  src/test/java/seedu/pivot/model/investigationcase/ReferenceTest.java
  src/test/java/seedu/pivot/storage/ReferenceStorageTest.java
  src/test/java/seedu/pivot/storage/StorageManagerTest.java
  src/test/java/seedu/pivot/storage/testutil/ReferenceStorageStub.java
Labels: priority.High, type.Enhancement

#157 [v1.3.2] Add Undo and Redo Commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/pivot/logic/commands/ClearCommand.java
  src/main/java/seedu/pivot/logic/commands/EditCommand.java
  src/main/java/seedu/pivot/logic/commands/RedoCommand.java
  src/main/java/seedu/pivot/logic/commands/UndoCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/AddCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/AddDescriptionCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/DeleteCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/AddDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/DeleteDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/AddSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/suspectcommands/DeleteSuspectCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/AddVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/victimcommands/DeleteVictimCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/AddWitnessCommand.java
  src/main/java/seedu/pivot/logic/commands/witnesscommands/DeleteWitnessCommand.java
  src/main/java/seedu/pivot/logic/parser/PivotParser.java
  src/main/java/seedu/pivot/model/Model.java
  src/main/java/seedu/pivot/model/ModelManager.java
  src/main/java/seedu/pivot/model/VersionedPivot.java
  src/test/java/seedu/pivot/logic/commands/ClearCommandTest.java
  src/test/java/seedu/pivot/logic/commands/casecommands/AddCaseCommandTest.java
  src/test/java/seedu/pivot/logic/commands/casecommands/AddDescriptionCommandTest.java
  src/test/java/seedu/pivot/logic/commands/casecommands/DeleteCaseCommandTest.java
  src/test/java/seedu/pivot/logic/commands/documentcommands/AddDocumentCommandTest.java
  src/test/java/seedu/pivot/logic/commands/documentcommands/DeleteDocumentCommandTest.java
  src/test/java/seedu/pivot/logic/commands/suspectcommands/AddSuspectCommandTest.java
  src/test/java/seedu/pivot/logic/commands/suspectcommands/DeleteSuspectCommandTest.java
  src/test/java/seedu/pivot/logic/commands/testutil/ModelStub.java
  src/test/java/seedu/pivot/logic/commands/victimcommands/AddVictimCommandTest.java
  src/test/java/seedu/pivot/logic/commands/victimcommands/DeleteVictimCommandTest.java
  src/test/java/seedu/pivot/logic/commands/witnesscommands/AddWitnessCommandTest.java
  src/test/java/seedu/pivot/logic/commands/witnesscommands/DeleteWitnessCommandTest.java
  src/test/java/seedu/pivot/model/PivotTest.java
  src/test/java/seedu/pivot/model/VersionedPivotTest.java
Labels: priority.High, type.Task

#163 Add support for EditCommand
  src/main/java/seedu/pivot/logic/commands/Command.java
  src/main/java/seedu/pivot/logic/commands/EditCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/EditTitleCommand.java
  src/main/java/seedu/pivot/logic/parser/EditCommandParser.java
  src/main/java/seedu/pivot/logic/parser/EditTitleCommandParser.java
  src/test/java/seedu/pivot/logic/commands/EditCommandTest.java
  src/test/java/seedu/pivot/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/pivot/logic/parser/PivotParserTest.java
Labels: priority.High, type.Task

#165 [v1.3.3] Add support for Edit Status and Edit Document
  src/main/java/seedu/pivot/commons/core/DeveloperMessages.java
  src/main/java/seedu/pivot/commons/core/UserMessages.java
  src/main/java/seedu/pivot/logic/commands/EditCommand.java
  src/main/java/seedu/pivot/logic/commands/OpenCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/EditStatusCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/EditTitleCommand.java
  src/main/java/seedu/pivot/logic/commands/casecommands/OpenCaseCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/EditDocumentCommand.java
  src/main/java/seedu/pivot/logic/commands/documentcommands/OpenDocumentCommand.java
  src/main/java/seedu/pivot/logic/parser/AddDocumentCommandParser.java
  src/main/java/seedu/pivot/logic/parser/EditCommandParser.java
  src/main/java/seedu/pivot/logic/parser/EditDocumentCommandParser.java
  src/main/java/seedu/pivot/logic/parser/EditStatusCommandParser.java
  src/main/java/seedu/pivot/logic/parser/OpenCommandParser.java
  src/test/data/JsonSerializablePivotTest/typicalPersonsPivot.json
  src/test/java/seedu/pivot/logic/commands/OpenDocumentCommandTest.java
  src/test/java/seedu/pivot/logic/parser/OpenCommandParserTest.java
  src/test/java/seedu/pivot/testutil/TypicalCases.java
Labels: priority.High, type.Task

#169 [v1.3.3] Update GUI
  src/main/java/seedu/pivot/logic/commands/ListCommand.java
  src/main/java/seedu/pivot/logic/commands/ListTabCommand.java
  src/main/java/seedu/pivot/logic/commands/OpenCommand.java
  src/main/java/seedu/pivot/logic/commands/archivecommands/ArchiveCommand.java
  src/main/java/seedu/pivot/logic/commands/archivecommands/ListArchiveCommand.java
  src/main/java/seedu/pivot/logic/commands/archivecommands/UnarchiveCommand.java
  src/main/java/seedu/pivot/logic/parser/ArchiveCommandParser.java
  src/main/java/seedu/pivot/logic/parser/ListCommandParser.java
  src/main/java/seedu/pivot/logic/parser/PivotParser.java
  src/main/java/seedu/pivot/logic/parser/UnarchiveCommandParser.java
  src/main/java/seedu/pivot/logic/state/StateManager.java
  src/main/java/seedu/pivot/ui/MainWindow.java
  src/main/java/seedu/pivot/ui/UiStateManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/pivot/logic/LogicManagerTest.java
  src/test/java/seedu/pivot/logic/commands/ListTabCommandTest.java
  src/test/java/seedu/pivot/logic/parser/ListCommandParserTest.java
Labels: priority.High, type.Task

#173 [v.1.3.3] Update User Guide for 1.3.3
  docs/UserGuide.md
Labels: priority.High, type.Task

#170 [v1.3.4] Update UserGuide
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.High, type.Task

#178 Update User Guide Collated 1
  docs/UserGuide.md
Labels: priority.High, type.Task

#182 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Task
